---
title: "ARC Figures"
author: Eva Jarvis
format: pdf
editor: visual
---

```{r}
#| label: load-packages-data
#| message: false
library(tidyverse)
library(dplyr)
library(readxl)
library(janitor)
library(ggplot2)
library(ggtext)
library(stringr)
library(patchwork)
```

```{r}
#| label: read-data

frequencies_renamed <- read_excel("Frequencies of PI and Cxn to CPS.xlsx") |>
  mutate(denominator = case_match(denominator,
                                  "imprisoned  people" ~ "Imprisoned People",
                                  "incarcerated parents" ~ "Incarcerated Parents",
                                  "foster care children" ~ "Foster Care Children",
                                  "CPS-involved children" ~ "CPS Involved-Children"
                                  ))

```

#Figure 1

```{r}
#| label: figure-one
#| fig-width: 11
#| fig-height: 4
frequencies_pivoted <- frequencies_renamed |>
  pivot_longer(cols = c(total, male, female, White, Black, Hispanic),
               names_to = "demographic",
               values_to = "proportion") |>
  filter(!is.na(proportion)) |>
  mutate(race = case_when(
    demographic %in% c("White", "Black", "Hispanic") ~ demographic,
    TRUE ~ "total"
  ),
  gender = case_when(demographic %in% c("male", "female") ~ demographic,
                     TRUE ~ "total"),
  cps_cj = if_else(denominator %in% c("Incarcerated Parents",
                                                 "Imprisoned People"),
                          "Criminal Justice Contact", 
                          "Child Protective Services Contact")) |>
  select(-demographic)

frequencies_pivoted |>
  ggplot(aes(x = proportion, y = clean_name, 
             fill = gender, shape = race)) +
  geom_point(size = 2, 
             position = position_jitter(height = .15, width = 0), 
             color = "black",
             show.legend = TRUE) +
  facet_wrap(~denominator, scales = "free_y") +
  scale_fill_manual(values = c("male" = "#86B6C3", "female" = "#D29141",
                                "total" = "white")) +
  scale_shape_manual(values = c("Black" = 22, "Hispanic" = 24, 
                                "White" = 23, "total" = 21)) +
  theme_bw() +
  theme(strip.background = element_rect(fill = NA),
        axis.title.y = element_blank(),
        strip.text.x = element_text(
          face = "plain",
          size = 11,
          margin = margin(t = 6, b = 6)
        ),
        plot.title = element_text(face = "bold"),
        text = element_text(size = 12),
        axis.text.y = element_markdown(),
        plot.caption.position = "plot",
        plot.caption = element_markdown(hjust = 0)) +
  guides(fill = guide_legend(
    override.aes = list(shape = 21, color = "black"))) +
  xlim(0, 0.75) +
  labs(title = "CPS Contact and Parental Incarceration",
       x = "Proportion of Population",
       y = "Condition",
       shape = "Race/Ethnicity",
       fill = "Gender")
```
#Figure 2

```{r}
#| label: figure-two
#| fig-width: 15
#| fig-height: 4
frequencies_mutated <- frequencies_renamed |>
  pivot_longer(cols = c(total, male, female, White, Black, Hispanic),
               names_to = "demographic",
               values_to = "proportion") |>
  filter(!is.na(proportion)) |>
  mutate(race = case_when(
    demographic %in% c("White", "Black", "Hispanic") ~ demographic,
    TRUE ~ "total"),
    race = fct_relevel(race, c("Hispanic", "White", "Black")),
    gender = case_when(demographic %in% c("male", "female") ~ demographic,
                     TRUE ~ "total"),
  alt_denominator = case_when(
    str_detect(clean_name,  "parental incarceration") ~ "Foster care and CPS-involved children",
    str_detect(clean_name, "Parental incarceration") ~ "Foster care and CPS-involved children",
    str_detect(clean_name, "Parent arrested") ~ "Foster care and CPS-involved children",
    TRUE ~ "Incarcerated people"),
  ) |>
  select(-demographic)

frequencies_mutated |>
  ggplot(aes(x = proportion, y = clean_name, 
             fill = gender, shape = race)) +
  geom_point(size = 2, 
             position = position_jitter(height = .15, width = 0), 
             color = "black",
             show.legend = TRUE) +
  facet_wrap(~alt_denominator, scales = "free_y") +
  scale_fill_manual(values = c("male" = "#86B6C3", "female" = "#D29141",
                                "total" = "white")) +
  scale_shape_manual(values = c("Black" = 22, "Hispanic" = 24, 
                                "White" = 23, "total" = 21)) +
  theme_bw() +
  theme(strip.background = element_rect(fill = NA),
        axis.title.y = element_blank(),
        strip.text.x = element_text(
          face = "plain",
          size = 11,
          margin = margin(t = 6, b = 6)
        ),
        plot.title = element_text(face = "bold"),
        text = element_text(size = 14),
        axis.text.y = element_markdown(),
        plot.caption.position = "plot",
        plot.caption = element_markdown(hjust = 0)) +
  guides(fill = guide_legend(
    override.aes = list(shape = 21, color = "black"))) +
  xlim(0, 0.75) +
  labs(title = "CPS Contact and Parental Incarceration",
       x = "Proportion of Population",
       y = "Condition",
       shape = "Race/Ethnicity",
       fill = "Gender")
  
```

#Figure 3 (Created for figure 6)

```{r}
#| label: figure-three
frequencies_mutated2 <- frequencies_mutated |>
  filter(denominator == "CPS Involved-Children")
  
p3 <- frequencies_mutated2 |>
  ggplot(aes(y = clean_name, x = proportion,
             fill = gender, shape = race)) + 
  geom_point(size = 2, 
             position = position_jitter(height = .15), 
             color = "black",
             show.legend = TRUE) +
  scale_fill_manual(values = c("male" = "#86B6C3", "female" = "#D29141",
                                "total" = "white")) +
  scale_shape_manual(values = c("Black" = 22, "Hispanic" = 24, 
                                "White" = 23, "total" = 21)) +
  scale_y_discrete(labels = c("Parent arrested prior to investigation" = 
                                "Parent arrested prior<br>to investigation"
                              )) +
  theme_bw() +
  theme(strip.background = element_rect(fill = NA),
        axis.title.y.left = element_blank(),
        axis.title.x = element_text(size = 10),
        strip.text.x = element_text(
          face = "plain",
          size = 11,
          margin = margin(t = 6, b = 6)
        ),
        plot.title = element_text(face = "bold",
                                  size = 12),
        text = element_text(size = 14),
        axis.text.y = element_markdown(size = 8),
        plot.caption.position = "plot",
        plot.caption = element_markdown(hjust = 0)) +
  guides(fill = guide_legend(
    override.aes = list(shape = 21, color = "black"))) +
  xlim(0, 0.75) +
  labs(title = "CPS-Involved Children",
       x = "% of CPS-Involved Children",
       y = "Condition",
       shape = "Race/Ethnicity",
       fill = "Gender")

```

#Figure 4 (Created for figure 6)

```{r}
#| label: figure-four
frequencies_mutated3 <- frequencies_mutated |>
  filter(denominator == "Foster Care Children")
  
p4 <- frequencies_mutated3 |>
  ggplot(aes(y = clean_name, x = proportion,
             fill = gender, shape = race)) + 
  geom_point(size = 2, 
             position = position_jitter(height = .15), 
             color = "black",
             show.legend = TRUE) +
  scale_fill_manual(values = c("male" = "#86B6C3", "female" = "#D29141",
                                "total" = "white")) +
  scale_shape_manual(values = c("Black" = 22, "Hispanic" = 24, 
                                "White" = 23, "total" = 21)) +
  scale_y_discrete(labels = c("Experiencing parental incarceration" = 
                                "Experiencing parental<br>incarceration",
                              "Foster care as a result of parental incarceration" = 
                                "Foster care as a<br>result of parental<br>incarceration"
                              )) +
  theme_bw() +
  theme(legend.position = "none",
        strip.background = element_rect(fill = NA),
        axis.title.y = element_blank(),
        axis.title.x = element_text(size = 10),
        strip.text.x = element_text(
          face = "plain",
          size = 11,
          margin = margin(t = 6, b = 6)
        ),
        plot.title = element_text(face = "bold",
                                  size = 12),
        text = element_text(size = 14),
        axis.text.y = element_markdown(size = 8),
        plot.caption.position = "plot",
        plot.caption = element_markdown(hjust = 0)) +
  guides(fill = guide_legend(
    override.aes = list(shape = 21, color = "black"))) +
  xlim(0, 0.75) +
  labs(x = "% of Foster Care Children",
       y = "Condition",
       shape = "Race/Ethnicity",
       fill = "Gender")
```

#Figure 5 (Created for figure 6)

```{r}
#| label: figure-five
frequencies_mutated4 <- frequencies_mutated |>
  filter(denominator == "Imprisoned People")
  
p5 <- frequencies_mutated4 |>
  ggplot(aes(y = clean_name, x = proportion,
             fill = gender, shape = race)) + 
  geom_point(size = 2, 
             position = position_jitter(height = .15), 
             color = "black",
             show.legend = TRUE) +
  scale_fill_manual(values = c("male" = "#86B6C3", "female" = "#D29141",
                                "total" = "white")) +
  scale_shape_manual(values = c("Black" = 22, "Hispanic" = 24, 
                                "White" = 23, "total" = 21)) +
  scale_y_discrete(labels = c("Is a parent" = 
                                "Is a<br>parent"
                              )) +
  theme_bw() +
  theme(legend.position = "none",
        strip.background = element_rect(fill = NA),
        axis.title.y = element_blank(),
        axis.title.x = element_text(size = 10),
        strip.text.x = element_text(
          face = "plain",
          size = 11,
          margin = margin(t = 6, b = 6)
        ),
        plot.title = element_text(face = "bold",
                                  size = 12),
        text = element_text(size = 14),
        axis.text.y = element_markdown(size = 8),
        plot.caption.position = "plot",
        plot.caption = element_markdown(hjust = 0)) +
  guides(fill = guide_legend(
    override.aes = list(shape = 21, color = "black"))) +
  xlim(0, 0.75) +
  labs(title = "Incarcerated Adults",
       x = "% of Imprisoned Adults",
       y = "Condition",
       shape = "Race/Ethnicity",
       fill = "Gender")
```

#Figure 6 (The product)

```{r}
#| label: figure-six
#| fig-width: 10
#| fig-height: 5
frequencies_mutated5 <- frequencies_mutated |>
  filter(denominator == "Incarcerated Parents")
  
p6 <- frequencies_mutated5 |>
  ggplot(aes(y = clean_name, x = proportion,
             fill = gender, shape = race)) + 
  geom_point(size = 2, 
             position = position_jitter(height = .15), 
             color = "black",
             show.legend = TRUE) +
  scale_fill_manual(values = c("male" = "#86B6C3", "female" = "#D29141",
                                "total" = "white")) +
  scale_shape_manual(values = c("Black" = 22, "Hispanic" = 24, 
                                "White" = 23, "total" = 21)) +
  scale_y_discrete(labels = c("Sole caretaker of child prior to arrest" = 
                                "Sole caretaker<br> of child prior<br>to arrest",
                              "Has a child in foster care" = 
                                "Has a child<br>in foster<br>care")) +
  theme_bw() +
  theme(legend.position = "none",
        strip.background = element_rect(fill = NA),
        axis.title.y = element_blank(),
        axis.title.x = element_text(size = 10),
        strip.text.x = element_text(
          face = "plain",
          size = 11,
          margin = margin(t = 6, b = 6)
        ),
        text = element_text(size = 14),
        axis.text.y = element_markdown(size = 8),
        plot.caption.position = "plot",
        plot.caption = element_markdown(hjust = 0)) +
  guides(fill = guide_legend(
    override.aes = list(shape = 21, color = "black")),
    shape = guide_legend(override.aes = list(color = "black"))) +
  xlim(0, 0.75) +
  labs(x = "% of Imprisoned Parents",
       y = "Condition",
       shape = "Race/Ethnicity",
       fill = "Gender")

(p3 + p5) / (p4 + p6) +
  plot_layout(guides = "collect")


```
